services:
  - type: web
    name: resume-parser
    env: python
    buildCommand: "pip install -r requirements-minimal.txt"
    startCommand: "gunicorn --config gunicorn.conf.py web_app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: HUGGINGFACE_HUB_TOKEN
        sync: false